### ISSUE TITLE
Struct: failed on block 2241767

### ISSUE THREAD

**Issue by ioannist** [KILTprotocol/kilt-node#418]
Our backend that indexes block success rates for https://stakekilt.com, is running into an issue at block 2241767 (or the one after) 

```
2022-10-05T06:19:34.554Z	889a5f14-3378-4e27-8703-23202096acac	ERROR	2022-10-05 06:19:34        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: createType(SignedBlock):: Struct: failed on block: {
    "header": "Header",
    "extrinsics": "Vec<Extrinsic>"
}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: findMetaCall: Unable to find Call with index [80, 4]/[80,4]

```
other indexers might face issues with it too, so maybe worth a look

all packages are up to date
    "@kiltprotocol/type-definitions": "0.2.1",
    "@polkadot/api": "9.4.3",

**Comment by jamesbayly** [comment]
We're also seeing this on https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fspiritnet.api.onfinality.io%2Fpublic-ws#/explorer/query/0x472fc36463fb9656ab5ea9537cbeacef778e04b8b3278019416ea201149ba0dd

**Comment by jamesbayly** [comment]
Found a solution with https://github.com/subquery/subql-starter/pull/73
