### ISSUE TITLE
Migration from Kusama to Polkadot

### ISSUE THREAD

**Issue by Chralt98** [KILTprotocol/kilt-node#484]
Hey valuable KILT maintainers,

In your technical Medium you posted the following:

> We’ll publish full documentation after the move to Polkadot is complete in late September, which should be helpful to other projects considering this path.

https://medium.com/kilt-protocol/kilt-migration-to-polkadot-technical-overview-ebc8c1700750

Harald at ZeitgeistPM has now published the technical steps to a successful migration. 

https://forum.polkadot.network/t/migrating-from-kusama-to-polkadot-a-complete-guide/2246

Kindly asking: Where can I find your "full documentation" of this process to match possible differences?

**Comment by weichweich** [comment]
Hi, unfortunately that was somehow forgotten. I'll read through Haralds guide. But I don't think there is much of a difference.
