### ISSUE TITLE
Cannot leave delagator after associated collator has left the network

### ISSUE THREAD

**Issue by sudipghimire533** [KILTprotocol/kilt-node#508]
## reproduce
- Join a collator `C` in network through `parachainStaking.joinCandidtae`
- Delegate amount `X` over collator `C`
- Leave the collator `C` through `parachainStaking.initLeaveCandidate` ( and wait )

## Expected
All the delegators who delegated in `C` will get their amount back as freeBalance or delegator should be able to call `initLeaveDelegator` to get the amount back

## Actual
Delegators amount is not returned when a candidateLeaves the network neither can delegator can call `initLeaveDelegator` afterwards

**Comment by weichweich** [comment]
Where did you see this `initLeaveDelegator` call?

As a delegator you call `leaveDelegators` when you want to stop delegating. In case your collator left, this is already done for everyone who delegated to that collator.
As a delegator you only need to unlock your coins after 7 Days.

* [how to unlock coins](https://docs.kilt.io/docs/participate/staking/unlock-unstaked/)
* [lifecycle of a delegator](https://docs.kilt.io/docs/participate/staking/delegate/lifecycle)
